apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-username/your-repo.git
    path: charts/hello-world
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
      # You can override values here too:
      values: |
        replicaCount: 3
        image:
          tag: "1.22"
        service:
          type: NodePort
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
