# Default values for hello-world
replicaCount: 2

image:
  repository: nginx
  tag: "1.21"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

nameOverride: ""
fullnameOverride: ""

labels: {}
annotations: {}

# Environment variables
env: []
  # - name: EXAMPLE_VAR
  #   value: "example-value"
