apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-world.fullname" . }}-service
  namespace: default
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "hello-world.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP
  type: {{ .Values.service.type }}
